"""initial schema

Revision ID: f612268343da
Revises: 
Create Date: 2026-05-12 16:51:38.828428
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f612268343da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('event_type', sa.Enum('demand_spike', 'seasonal_change', 'supply_disruption', 'weather_event', 'route_disruption', 'inventory_alert', 'reorder_trigger', name='eventtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Enum('scheduled', 'emergency', name='eventpriority'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('lead_time_hours', sa.Float(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('scenarios', sa.JSON(), nullable=False),
    sa.Column('selected_scenario', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceo_decisions',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('all_scenarios', sa.JSON(), nullable=False),
    sa.Column('selected_action', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('causal_chain', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_records',
    sa.Column('trigger_type', sa.Enum('low_confidence', 'no_viable_action', 'ambiguous_recommendation', name='escalationtrigger'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('scenarios_considered', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', name='escalationpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'acknowledged', 'resolved', 'overridden', 'auto_expired', name='escalationstatus'), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_policies',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('reorder_quantity', sa.Float(), nullable=False),
    sa.Column('max_stock', sa.Float(), nullable=False),
    sa.Column('spoilage_rate_per_day', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('typical_hours', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_history',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.Enum('SupplyGap', 'DemandSpike', 'RouteDisruption', 'InventoryAlert', 'SeasonalShift', name='signaltype'), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('sensor', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('sales_history')
    op.drop_table('routes')
    op.drop_table('inventory_policies')
    op.drop_table('inventory')
    op.drop_table('escalation_records')
    op.drop_table('ceo_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_table('events')
    op.drop_table('companies')
    # ### end Alembic commands ###
